export const SELECT_VEHICLE_DATA = 'SELECT_VEHICLE_DATA';
export const HIDE_IMAGE_CROPPER = 'HIDE_IMAGE_CROPPER';
export const SET_VEHICLE_IMAGE = 'SET_VEHICLE_IMAGE';
export const SHOW_IMAGE_CROPPER = 'SHOW_IMAGE_CROPPER';
export const CLEAR_VEHICLE_IMAGE = 'CLEAR_VEHICLE_IMAGE';